[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/san-pham"
  to = "/san-pham.html"
  status = 301

[[redirects]]
  from = "/giai-phap"
  to = "/giai-phap.html"
  status = 301

[[redirects]]
  from = "/khach-hang"
  to = "/khach-hang.html"
  status = 301

[[redirects]]
  from = "/ve-chung-toi"
  to = "/ve-chung-toi.html"
  status = 301
